version: '3'
services:
    server:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - ./server:/app
        stdin_open: true
            
